CREATE DATABASE IF NOT EXISTS DATA_LAB;
CREATE ROLE IF NOT EXISTS DLT_LOADER_ROLE;
CREATE USER IF NOT EXISTS LOADER PASSWORD = '<sua-senha>' DEFAULT_ROLE = DLT_LOADER_ROLE;

GRANT ROLE DLT_LOADER_ROLE TO USER LOADER;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DLT_LOADER_ROLE;
GRANT USAGE ON DATABASE DATA_LAB TO ROLE DLT_LOADER_ROLE;
GRANT CREATE SCHEMA ON DATABASE DATA_LAB TO ROLE DLT_LOADER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE DATA_LAB TO ROLE DLT_LOADER_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE DATA_LAB TO ROLE DLT_LOADER_ROLE;