GRANT USAGE ON WAREHOUSE SNOWFLAKE_LEARNING_WH TO ROLE DLT_LOADER_ROLE;
GRANT USAGE ON DATABASE DATA_LAB TO ROLE DLT_LOADER_ROLE;
GRANT USAGE ON SCHEMA DATA_LAB.BRONZE TO ROLE DLT_LOADER_ROLE;
GRANT CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT
    ON SCHEMA DATA_LAB.BRONZE TO ROLE DLT_LOADER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
    ON ALL TABLES IN SCHEMA DATA_LAB.BRONZE TO ROLE DLT_LOADER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
    ON FUTURE TABLES IN SCHEMA DATA_LAB.BRONZE TO ROLE DLT_LOADER_ROLE;

GRANT USAGE ON WAREHOUSE SNOWFLAKE_LEARNING_WH TO ROLE DBT_TRANSFORMER_ROLE;
GRANT USAGE ON DATABASE DATA_LAB TO ROLE DBT_TRANSFORMER_ROLE;
GRANT USAGE ON SCHEMA DATA_LAB.BRONZE TO ROLE DBT_TRANSFORMER_ROLE;
GRANT SELECT
    ON ALL TABLES IN SCHEMA DATA_LAB.BRONZE TO ROLE DBT_TRANSFORMER_ROLE;
GRANT SELECT
    ON FUTURE TABLES IN SCHEMA DATA_LAB.BRONZE TO ROLE DBT_TRANSFORMER_ROLE;
GRANT SELECT
    ON ALL VIEWS IN SCHEMA DATA_LAB.BRONZE TO ROLE DBT_TRANSFORMER_ROLE;
GRANT SELECT
    ON FUTURE VIEWS IN SCHEMA DATA_LAB.BRONZE TO ROLE DBT_TRANSFORMER_ROLE;

GRANT USAGE ON SCHEMA DATA_LAB.SILVER TO ROLE DBT_TRANSFORMER_ROLE;
GRANT CREATE TABLE, CREATE VIEW
    ON SCHEMA DATA_LAB.SILVER TO ROLE DBT_TRANSFORMER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
    ON ALL TABLES IN SCHEMA DATA_LAB.SILVER TO ROLE DBT_TRANSFORMER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
    ON FUTURE TABLES IN SCHEMA DATA_LAB.SILVER TO ROLE DBT_TRANSFORMER_ROLE;
GRANT SELECT, REFERENCES
    ON ALL VIEWS IN SCHEMA DATA_LAB.SILVER TO ROLE DBT_TRANSFORMER_ROLE;
GRANT SELECT, REFERENCES
    ON FUTURE VIEWS IN SCHEMA DATA_LAB.SILVER TO ROLE DBT_TRANSFORMER_ROLE;

GRANT USAGE ON SCHEMA DATA_LAB.GOLD TO ROLE DBT_TRANSFORMER_ROLE;
GRANT CREATE TABLE, CREATE VIEW
    ON SCHEMA DATA_LAB.GOLD TO ROLE DBT_TRANSFORMER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
    ON ALL TABLES IN SCHEMA DATA_LAB.GOLD TO ROLE DBT_TRANSFORMER_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES
    ON FUTURE TABLES IN SCHEMA DATA_LAB.GOLD TO ROLE DBT_TRANSFORMER_ROLE;
GRANT SELECT, REFERENCES
    ON ALL VIEWS IN SCHEMA DATA_LAB.GOLD TO ROLE DBT_TRANSFORMER_ROLE;
GRANT SELECT, REFERENCES
    ON FUTURE VIEWS IN SCHEMA DATA_LAB.GOLD TO ROLE DBT_TRANSFORMER_ROLE;
