CREATE USER IF NOT EXISTS LOADER
    TYPE = PERSON
    PASSWORD = '<% loader_password %>'
    DEFAULT_ROLE = DLT_LOADER_ROLE
    DEFAULT_WAREHOUSE = SNOWFLAKE_LEARNING_WH
    DEFAULT_NAMESPACE = DATA_LAB.BRONZE
    DEFAULT_SECONDARY_ROLES = ();

ALTER USER IF EXISTS LOADER SET
    TYPE = PERSON
    PASSWORD = '<% loader_password %>'
    DEFAULT_ROLE = DLT_LOADER_ROLE
    DEFAULT_WAREHOUSE = SNOWFLAKE_LEARNING_WH
    DEFAULT_NAMESPACE = DATA_LAB.BRONZE
    DEFAULT_SECONDARY_ROLES = ();

GRANT ROLE DLT_LOADER_ROLE TO USER LOADER;

CREATE USER IF NOT EXISTS DBT_TRANSFORMER
    TYPE = PERSON
    PASSWORD = '<% dbt_transformer_password %>'
    DEFAULT_ROLE = DBT_TRANSFORMER_ROLE
    DEFAULT_WAREHOUSE = SNOWFLAKE_LEARNING_WH
    DEFAULT_NAMESPACE = DATA_LAB.SILVER
    DEFAULT_SECONDARY_ROLES = ();

ALTER USER IF EXISTS DBT_TRANSFORMER SET
    TYPE = PERSON
    PASSWORD = '<% dbt_transformer_password %>'
    DEFAULT_ROLE = DBT_TRANSFORMER_ROLE
    DEFAULT_WAREHOUSE = SNOWFLAKE_LEARNING_WH
    DEFAULT_NAMESPACE = DATA_LAB.SILVER
    DEFAULT_SECONDARY_ROLES = ();

GRANT ROLE DBT_TRANSFORMER_ROLE TO USER DBT_TRANSFORMER;
