CREATE USER IF NOT EXISTS LOADER
    TYPE = PERSON
    PASSWORD = '<% loader_password %>'
    DEFAULT_ROLE = DLT_LOADER_ROLE
    DEFAULT_WAREHOUSE = SNOWFLAKE_LEARNING_WH
    DEFAULT_NAMESPACE = DATA_LAB.BRONZE
    DEFAULT_SECONDARY_ROLES = ();

ALTER USER IF EXISTS LOADER SET
    TYPE = PERSON
    PASSWORD = '<% loader_password %>'
    DEFAULT_ROLE = DLT_LOADER_ROLE
    DEFAULT_WAREHOUSE = SNOWFLAKE_LEARNING_WH
    DEFAULT_NAMESPACE = DATA_LAB.BRONZE
    DEFAULT_SECONDARY_ROLES = ();

GRANT ROLE DLT_LOADER_ROLE TO USER LOADER;
GRANT ROLE DBT_TRANSFORMER_ROLE TO USER LOADER;
