CREATE USER IF NOT EXISTS LOADER
    TYPE = SERVICE
    DEFAULT_ROLE = DLT_LOADER_ROLE
    DEFAULT_WAREHOUSE = SNOWFLAKE_LEARNING_WH
    DEFAULT_NAMESPACE = DATA_LAB.BRONZE
    DEFAULT_SECONDARY_ROLES = ()
    RSA_PUBLIC_KEY = '<% loader_public_key %>';

ALTER USER IF EXISTS LOADER SET
    TYPE = SERVICE
    DEFAULT_ROLE = DLT_LOADER_ROLE
    DEFAULT_WAREHOUSE = SNOWFLAKE_LEARNING_WH
    DEFAULT_NAMESPACE = DATA_LAB.BRONZE
    DEFAULT_SECONDARY_ROLES = ()
    RSA_PUBLIC_KEY = '<% loader_public_key %>';

GRANT ROLE DLT_LOADER_ROLE TO USER LOADER;

CREATE USER IF NOT EXISTS DBT_TRANSFORMER
    TYPE = SERVICE
    DEFAULT_ROLE = DBT_TRANSFORMER_ROLE
    DEFAULT_WAREHOUSE = SNOWFLAKE_LEARNING_WH
    DEFAULT_NAMESPACE = DATA_LAB.SILVER
    DEFAULT_SECONDARY_ROLES = ()
    RSA_PUBLIC_KEY = '<% dbt_transformer_public_key %>';

ALTER USER IF EXISTS DBT_TRANSFORMER SET
    TYPE = SERVICE
    DEFAULT_ROLE = DBT_TRANSFORMER_ROLE
    DEFAULT_WAREHOUSE = SNOWFLAKE_LEARNING_WH
    DEFAULT_NAMESPACE = DATA_LAB.SILVER
    DEFAULT_SECONDARY_ROLES = ()
    RSA_PUBLIC_KEY = '<% dbt_transformer_public_key %>';

GRANT ROLE DBT_TRANSFORMER_ROLE TO USER DBT_TRANSFORMER;
